import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black text-neutral-100">
      <body className="antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
