import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import localFont from "next/font/local";
import clsx from "clsx";
import Header from "~/components/Header";
import Footer from "~/components/Footer";

const neue = localFont({
  src: "../../public/fonts/NeueHaasUnica-ExtraLight.woff2",
  weight: "300",
  variable: "--font-neue",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx("bg-black text-white", neue.variable)}>
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
